function [helpbox,help_general,help_max_slip,help_slipdist,help_imp] = uihelp(tab1,p1,p2,p3,p5)
%this script only contains functions for the ? - buttons on the ui
%set up helpbox:
text = sprintf('\n\t\t\t\t\t\t\t3D - Faults v 1.6');

helpbox = uitextarea(tab1,'Position',[855 355 485 270],'Value',text,'Editable','off');

% '?' - buttons:
help_general = uibutton(p1,'push','Text','?','Position',[800,20,20,20],'BackgroundColor',[.3 .8 .8],'FontWeight','bold','FontSize',12,'ButtonPushedFcn',@(help_general,event) uihelp_general(helpbox));
help_slipdist = uibutton(p2,'push','Text','?','Position',[240,10,20,20],'BackgroundColor',[.3 .8 .8],'FontWeight','bold','FontSize',12,'ButtonPushedFcn',@(help_slipdist,event) uihelp_slipdist(helpbox));
help_max_slip = uibutton(p3,'push','Text','?','Position',[240,10,20,20],'BackgroundColor',[.3 .8 .8],'FontWeight','bold','FontSize',12,'ButtonPushedFcn',@(help_max_slip,event) uihelp_max_slip(helpbox));
help_imp = uibutton(p5,'push','Text','?','Position',[250,10,40,40],'BackgroundColor',[.3 .8 .8],'FontWeight','bold','FontSize',14,'ButtonPushedFcn',@(help_imp,event) uihelp_imp(helpbox));

%% functions
function helpbox = uihelp_general(helpbox)
    helptext = sprintf(strcat(('GENERAL SETTINGS:\n\n'),...
        ('File name: Name for the output file that will be created\n'),...
        ('Grid size: The size of the rectangular elements along strike.\n'),...
        ('Coulomb grid size: Grid size for calculating the Coulomb stress transferred at a specified depth.\n')));
    set(helpbox,'Value',helptext);
end
function helpbox = uihelp_slipdist(helpbox)
    helptext = sprintf(strcat(('INFORMATION TO BUILD THE SLIP DISTRIBUTION \n\n'),...
        ('Slip at surface: What fraction of the maximum slip at depth occurs at the surface.\n'),...
        ('Maximum slip (m): Defines the maximum slip at the center of the bulls eye slip distribution\n\n'),...
        ('Seismogenic depth: Depth of the seismogenic zone in kilometres\n'),...
        ('Rupture depth: 0 = default - the fault ruptures the whole seismogenic zone. Change to down-dip extent (in km).')));
    set(helpbox,'Value',helptext);
end
function helpbox = uihelp_max_slip(helpbox)
    helptext = sprintf(strcat(('SETTING THE LOCATION OF MAXIMUM SLIP\n\n'),...
        ('Default setting is to have the location of maximum slip in the centre of the fault'),...
        (' to generate a symmetric concentric slip distribution.\n\n'),...
        ('Horizontal centre: Change to distance (in km) from the north/west end to control the location of'),...
        (' maximum slip along the fault. This must be less than length of the fault that ruptures.\n'),...
        ('Vertical centre: Change to distance (in km) from the surface to control the location of'),...
        (' maximum slip down-dip of the fault. This must be less than the rupture depth.')));
    set(helpbox,'Value',helptext);
end
function helpbox = uihelp_imp(helpbox)
    helptext = sprintf(strcat(('FAULT INPUT FORMATS: \n\n'),...
        (' .shp - ESRI shapefile: Fault traces and properties are imported from a single shapefile.\n\n'),...
        (' .kml-files: choose a table (e.g. .txt, .csv, .xlsx) that contains all fault properties. '),...
        ('  kml files of all faults must be stored in the Faults_3D/Fault_traces folder.\n\n'),...
        (' .kmz-file: a kmz-file containing the fault traces and a table containing the properties '),...
        ('  are imported separately.\n\n'),...
        ('Make sure that the input files are formatted appropriately! See README and input examples.')));
    set(helpbox,'Value',helptext);
end
end
